### ISSUE TITLE
Remove workaround locks

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap-daemon#78] opened 2016-04-04 13:38 UTC
We have solved occasional tracebacks within atomic mount using locks. However this is only a workaround. This issue is a reminder that it is not a final solution.
See https://github.com/OpenSCAP/openscap-daemon/issues/58

**Comment by mpreisler** [comment] 2016-04-04 13:42
See https://github.com/OpenSCAP/openscap-daemon/blob/master/openscap_daemon/cve_scanner/scan.py#L38

This only affects the `cve_scanner` module in openscap_daemon. Please note that `cve_scanner` module is going to be deprecated and unused soon.

**Comment by mpreisler** [comment] 2016-08-10 15:50
If we decide to do this for 0.2.0, #93 will be enough to solve this bug.

**Comment by matejak** [comment] 2018-10-03 14:44
Closing as sortof duplicate of #93

**Closed by matejak** 2018-10-03 14:44 UTC
